# Generated by Django 4.2.7 on 2023-11-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="processed_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="processed_images/"
            ),
        ),
    ]
