# Generated by Django 4.2.7 on 2023-11-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photoapp", "0002_alter_photo_processed_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="media/photos/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="processed_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/processed_images/"
            ),
        ),
    ]
