# Generated by Django 4.2.7 on 2023-11-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photoapp", "0005_news_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="new",
        ),
    ]
