# Generated by Django 4.2.7 on 2023-11-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photoapp", "0006_remove_news_new"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="Newses",
        ),
    ]
