# Generated by Django 4.2.7 on 2023-11-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photoapp", "0007_rename_news_newses"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date_published", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Newses",
        ),
    ]
